# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: test-k
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: s-container
          image: samir3112/c-apache:v1
          ports:
            - containerPort: 80


# kubectl create namespace test-k
# kubectl config set-context --current --namespace=test-k
# kubectl apply -f deployment.yaml
# kubectl get pods
# kubectl scale deployment apache-deployment --replicas=4
# kubectl get deployments
# kubectl config view --minify | grep namespace
# also used kubectl get namespaces