# Step 1: Use a Red Hat UBI 8 base image
FROM registry.access.redhat.com/ubi8/ubi:latest

# Step 2: Update the system and install Apache
RUN yum update -y && yum install -y httpd
    

# Step 3: Set the working directory
WORKDIR /var/www/html

# Step 4: Copy the index.html file to the document root
COPY index.html /var/www/html/index.html

# Step 5: Expose port 80
EXPOSE 80

# Step 6: Set the entrypoint to run Apache in the foreground
ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]

# 1st Program
# docker build -t samir3112/c-apache:v1 .
# docker run -d -p 8080:80 samir3112/c-apache:v1
# docker ps -a
# docker inspect <container id>
# IP address
# curl http:// IP address:80


# 2nd Program
# docker build -t samir3112/c-apache:v1 .
# docker run -d -p 8080:80 -d -v $(pwd)/changes/file_host:/var/www/html/index.html samir3112/c-apache:v1 
# docker volume ls
# GET  data
# curl  'http://localhost:80'